stages:
  - deploy_to_local
  - deploy_to_local_staging


build_and_deploy_to_local:
  stage: deploy_to_local
  script:
    - echo "Deploying to local environment"
    - echo "-----------------------------------------------------------------"
    - cat $ENV_FILE
    - cat $ENV_FILE | sed 's/\"//g' > .env
    - docker network inspect backendnetwork >/dev/null 2>&1 || docker network create backendnetwork
    - docker-compose down
    - docker-compose up --build -d
  tags:
    - dockerexecutor
  only:
    - dev

deploy_to_local_staging:
  stage: deploy_to_local_staging
  script:
    - echo "Deploying to local staging environment"
    - echo "-----------------------------------------------------------------"
    - docker network inspect backendnetwork >/dev/null 2>&1 || docker network create backendnetwork
    - docker-compose down
    - docker-compose -f docker-compose.staging.yml up --build -d
  tags:
    - dockerexecutor
  only:
    - staging