stages:
  - build_container
  - deploy_to_local
  - update_golden_records
  - deploy_to_local_staging


build_container:
  stage: build_container
  script:
    - echo "Building the app"
    - echo "-----------------------------------------------------------------"
    - echo "NOTE THAT ENV_FILE is a variable set up in the gitlab project settings CI/CD section Variables"
    - echo $ENV_FILE | sed 's/ /\n/g'
    - echo $ENV_FILE | sed 's/ /\n/g' > .env
    - docker network inspect backendnetwork >/dev/null 2>&1 || docker network create backendnetwork
    - docker-compose down
    - docker-compose build
  tags:
    - dockerexecutor
  only:
    - dev



deploy_to_local:
  stage: deploy_to_local
  script:
    - echo "Deploying to local environment"
    - echo "-----------------------------------------------------------------"
    - echo $ENV_FILE | sed 's/ /\n/g'
    - echo $ENV_FILE | sed 's/ /\n/g' > .env
    - docker-compose up -d
  tags:
    - dockerexecutor
  only:
    - dev


# add step to run the setup_golden_records.py script at the end
update_golden_records:
  stage: update_golden_records
  script:
    - echo "Checking that the containers are running"
    - echo "-----------------------------------------------------------------"
    - docker ps
    - echo ""
    - echo "Wait for 10 seconds for the database to be ready"
    - sleep 10
    - echo "Updating golden records"
    - echo "-----------------------------------------------------------------"
    - docker exec -t dataherald-app-1 sh -c "cd scripts && python3 setup_golden_records.py"
  tags:
    - dockerexecutor
  only:
    - dev
    

deploy_to_local_staging:
  stage: deploy_to_local_staging
  script:
    - echo "Deploying to local staging environment"
    - echo "-----------------------------------------------------------------"
    - docker-compose -f docker-compose.staging.yml up -d
  tags:
    - dockerexecutor
  only:
    - staging