services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3001:3001"
    command: uvicorn app:app --host 0.0.0.0 --port 3001 --log-level debug --reload
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    networks:
      - dataherald_network
networks:
  dataherald_network:
    external: true
